---
- name: check hostname
  shell: uname -n
  changed_when:
    - reg_hostname.stdout != openstack_common.hostname
  register: reg_hostname
  notify:
    - reboot target
    - wait for ssh close
    - wait for ssh open

- block:
  - name: change hostname
    shell: echo {{ openstack_common.hostname }} > /etc/hostname
    when:
      - reg_hostname | changed

  - name: set /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts

  - name: disable and stopped firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
  become: yes
